# This is a basic workflow to help you get started with Actions

name: googlesheet-actions

# Do things every 5 minutes
on: workflow_dispatch
#  schedule:
#    - cron: "*/5 * * * *"

jobs:
    fetch:
      runs-on: ubuntu-latest
      steps:
        - id: googlesheet_actions
          uses: enstars/googlesheet-actions@master
          with:
            sheet-id: ${{ secrets.SHEET_ID }}
        - id: echo
          uses: actions/github-script@v2
          with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
                console.log(${{steps.googlesheet_actions.outputs.result}})
        - name: test
          run: |
            cat $HOME/data.json
